#ifndef __CPU_COMM_ID_H__
#define __CPU_COMM_ID_H__

typedef enum _CPU_COMM_ID {
  CPU_COMM_ID_SYSFLAG = 0,
  CPU_COMM_ID_UART,
  CPU_COMM_ID_TESTA2B ,    
  CPU_COMM_ID_MDA2B,  
  CPU_COMM_ID_AECA2B, 
  CPU_COMM_ID_AACA2B,
  CPU_COMM_ID_AESA2B,
  CPU_COMM_ID_V4L2A2B,
  CPU_COMM_ID_ALSAA2B,  
  CPU_COMM_ID_CMD,
  CPU_COMM_ID_OKAOFD,
  CPU_COMM_ID_WD,
  CPU_COMM_ID_I2C,
  CPU_COMM_ID_MDB2A = CPU_COMM_ID_MDA2B, 
  CPU_COMM_ID_AECB2A = CPU_COMM_ID_AECA2B,

  CPU_COMM_ID_AACB2A = CPU_COMM_ID_AACA2B, 
  CPU_COMM_ID_AESB2A = CPU_COMM_ID_AESA2B,
  
  CPU_COMM_ID_V4L2B2A = CPU_COMM_ID_V4L2A2B, 
  CPU_COMM_ID_ALSAB2A = CPU_COMM_ID_ALSAA2B, 
  CPU_COMM_ID_SOCKET=0x40,
  // this is the end of ID enumeration
  CPUCOMM_ID_MAX_NUM,

  // illeagle ID
  CPU_COMM_ID_ILLEGAL=0xEE // fixed same value between cpu-a and cpu-b,or you got surprise
} CPU_COMM_ID;


#endif // __CPU_COMM_ID_H__

